pipeline:

    npm:install:
        image: node
        commands:
            - npm install --silent --progress=false

    npm:build:
        image: node
        environment:
            - "VERSION=${DRONE_COMMIT_SHA}"
            - "FLAVOUR=${DRONE_COMMIT_BRANCH}"
            - "SENTRY_DSN=${SENTRY_DSN}"
        commands:
            -  npm run build:prod

    docker:deploy:
        image: plugins/docker
        repo: chieftan/frontend
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"
