pipeline:

    npm:install:
        image: node:6-slim
        commands:
            - npm install --silent --progress=false

    npm:build:
        image: node:6-slim
        environment:
            - VERSION=$DRONE_COMMIT_SHA
            - FLAVOUR=$DRONE_COMMIT_BRANCH
            - SENTRY_DSN=$SENTRY_DSN
        commands:
            - npm run build:prod

    docker:
        repo: chieftan/frontend
        tag:
            - latest
            - "${DRONE_COMMIT_BRANCH}"
        username: "${DOCKER_USERNAME}"
        password: "${DOCKER_PASSWORD}"
        email: "${DOCKER_EMAIL}"
        build_args:
            - "VERSION=${DRONE_COMMIT_SHA}"
